### ISSUE TITLE
Should normal samples in the test set also need mask?

### ISSUE THREAD

**Issue by Karma1628** [MaticFuc/ECCV_TransFusion#2]

**Comment by MaticFuc** [comment]
No. 

If you are referring to the foreground masks, they are only used during training. If you refer to anomaly masks, they do not require them, as the empty mask is the ground truth.

**Comment by Karma1628** [comment]
![1725348066623](https://github.com/user-attachments/assets/290da768-65f7-4efa-8191-bc44f6a9ba14)
I encountered this warning when running the code, and it seems related to finding masks for normal samples in the test set. Is it safe to ignore this warning?

**Comment by MaticFuc** [comment]
Yes, it is safe to ignore this warning. The warning comes from `Dataset.py` line 28.

**Comment by Karma1628** [comment]
Ok, thank you very much!
