### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by nanbowan6662** [MaticFuc/ECCV_TransFusion#4]
Hello, I did not change any code, but after running it, I encountered this error message. I don't know how to resolve it.
![f608fb7cecd29b6a1a138e6dd0db3a2](https://github.com/user-attachments/assets/e58953d5-c7a3-4eba-9dec-c8e593320f80)
![ab1eb61cdf77751ede74261e1adc110](https://github.com/user-attachments/assets/1c2e6a12-f7d5-42d9-ac95-527451600dfc)
Looking forward to your reply, thanks!

**Comment by nanbowan6662** [comment]
And I failed to run download_fg_masks.sh to download the foreground masks. Is this file necessary to download?  ❀

**Comment by MaticFuc** [comment]
What error are you getting when you run `download_fg_masks.sh`?

**Comment by nanbowan6662** [comment]
> What error are you getting when you run `download_fg_masks.sh`?

It turns out that the download failed due to network problems. After the file is downloaded, the error no longer exists. Thanks!
