### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by xgzng** [MaticFuc/ECCV_TransFusion#5]
Hello, may I ask how Transfusion evaluates pixel AUC metrics on MVTEC and Visa?

**Comment by MaticFuc** [comment]
Hi,

the pixel-level AUROC are as following:

- MVTec3D: 99.3%
- MVTec 96.8 %
- VisA 98.4%

I've added the calculation of this metrics to the code as well and per-category results can be found in the `results` directory.

**Comment by xgzng** [comment]
OK, thank you very much!
