### ISSUE TITLE
VisA dataset erro

### ISSUE THREAD

**Issue by 0neLastK1ss** [MaticFuc/ECCV_TransFusion#6]
![1](https://github.com/user-attachments/assets/08365603-4bb6-45e5-84a0-1197abb964ed)

When I switched to the VisA dataset, this error occurred, which means my dataset is empty. However, when I switched back to the mvtec dataset, everything worked fine. I checked the relevant paths and found no issues. Can you help me resolve this problem? Thank you very much.

**Comment by MaticFuc** [comment]
It works on my side.

Check if the `--dataset` argument is set to `visa` and if you split the data to mimic the MVTec AD Dataset (how to do that is described here: [https://github.com/amazon-science/spot-diff](https://github.com/amazon-science/spot-diff).

If both are correct and it doesn't work please message me.

**Comment by 0neLastK1ss** [comment]
My issue has been resolved, thank you very much for your help!
